<?xml version="1.0" encoding="utf-8"?>
<Project>
	<!-- Set hardcoded version for all projects -->
	<PropertyGroup>
		<AssemblyVersion>1.8.5</AssemblyVersion>
		<FileVersion>1.8.5</FileVersion>
		<Version>1.8.5</Version>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="$(MSBuildThisFileDirectory)Shared\AppInfo.cs" Link="AppInfo.cs" />
	</ItemGroup>
</Project>
